---

- hosts: all
  become: true
  become_method: su
  become_user: root
  vars_files:
    - ./vars/users.yml

  tasks:
  - name: Installing pre-req
    apt:
      update_cache:  yes
      name: "{{ pre_req }}"
      state: present

  - name: Ensure group admins exists 
    group:
        name: "{{ item }}"
        state: present
    with_items: "{{ group }}"
    register: result

  - name: "Create user accounts and add users to groups"
    user:
        name: "{{ item }}"
        groups: "{{ group }}"
        shell: "{{ shell }}"
    with_items: "{{ users }}"
    register: result 

  - name: Debuginfo
    debug:
        var: result


 


  
     